//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__Z17swap_flot32_arrayPci(SB), $0-16

    MOVQ buf+0(FP), DI
    MOVQ len+8(FP), SI

    WORD $0xf685                 // test    esi, esi
	JE LBB0_3
    WORD $0x6348; BYTE $0xc6     // movsxd    rax, esi
    WORD $0xc931                 // xor    ecx, ecx
LBB0_2:
    WORD $0x148b; BYTE $0x0f     // mov    edx, dword [rdi + rcx]
    WORD $0xca0f                 // bswap    edx
    WORD $0x1489; BYTE $0x0f     // mov    dword [rdi + rcx], edx
    LONG $0x04c18348             // add    rcx, 4
    WORD $0x3948; BYTE $0xc1     // cmp    rcx, rax
	JB LBB0_2
LBB0_3:
    RET




TEXT ·__Z19big_endian_to_floatPc(SB), $0-16

    MOVQ buf+0(FP), DI

    LONG $0x2cfae1c4; BYTE $0x07 // vcvttss2si    rax, dword [rdi]
    WORD $0xc80f                 // bswap    eax
    LONG $0x2afae1c4; BYTE $0xc0 // vcvtsi2ss    xmm0, xmm0, rax
    MOVQ AX, v+8(FP)
    RET
