//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__Z11write_floatPfPc(SB), $0-16

    MOVQ v+0(FP), DI
    MOVQ buf+8(FP), SI

    LONG $0xfa1e0ff3             // endbr64
    WORD $0x06c6; BYTE $0x02     // mov    BYTE PTR [rsi], 2
    WORD $0x078b                 // mov    eax, DWORD PTR [rdi]
    WORD $0x4689; BYTE $0x01     // mov    DWORD PTR 1[rsi], eax
    RET
