//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__Z11write_floatPfPc(SB), $0-16

    MOVQ v+0(FP), DI
    MOVQ buf+8(FP), SI

    WORD $0x06c6; BYTE $0x02     // mov    byte [rsi], 2
    WORD $0x078b                 // mov    eax, dword [rdi]
    WORD $0x4689; BYTE $0x01     // mov    dword [rsi + 1], eax
    RET
